# Generated by Django 3.2.9 on 2021-11-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211128_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
