# Generated by Django 3.2.9 on 2021-11-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211128_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
